export type Palettes =
  | 'Default'
  | 'Random Cycle'
  | 'Primary Color'
  | 'Based on Primary'
  | 'Set Colors'
  | 'Based on Set'
  | 'Party'
  | 'Cloud'
  | 'Lava'
  | 'Ocean'
  | 'Forest'
  | 'Rainbow'
  | 'Rainbow Bands'
  | 'Sunset'
  | 'Rivendell'
  | 'Breeze'
  | 'Red & Blue'
  | 'Yellowout'
  | 'Analogous'
  | 'Splash'
  | 'Pastel'
  | 'Sunset 2'
  | 'Beech'
  | 'Vintage'
  | 'Departure'
  | 'Landscape'
  | 'Beach'
  | 'Sherbet'
  | 'Hult'
  | 'Hult 64'
  | 'Drywet'
  | 'Jul'
  | 'Grintage'
  | 'Rewhi'
  | 'Tertiary'
  | 'Fire'
  | 'Icefire'
  | 'Cyane'
  | 'Light Pink'
  | 'Autumn'
  | 'Magenta'
  | 'Magred'
  | 'Yelmag'
  | 'Yelblu'
  | 'Orange & Teal'
  | 'Tiamat'
  | 'April Night'
  | string;
