name: 'WLED Buildlight'
description: 'Provide a description here'
author: 'jameswlane'
inputs:
  url:
    description: 'URL or IP address to WLED'
    required: true
  palette:
    description: 'Palette Name'
    required: false
  effect:
    required: false
    description: 'Effect Overlay'
runs:
  using: 'node18'
  main: 'dist/index.js'